baseURL = 'https://drh.github.io/'
locale = 'en-us'
title = 'David R. Hanson'
uglyURLs = true
disableKinds = [ "rss", "sitemap", "taxonomy", "term" ]
[security]
  allowContent = ['^text/html$']
enableGitInfo = true
[frontmatter]
  lastmod = [ ':fileModTime', ':git', ':default' ]
